from functools import lru_cache


@lru_cache()
def alpha_3_code(name):
    if len(name) == 3 and name.isupper():
        return name
    for alpha_3, country_name in alpha_3_to_name.items():
        if country_name == name:
            return alpha_3


alpha_3_to_name = {
    "AFG": "Afghanistan",
    "ALB": "Albania",
    "ALG": "Algeria",
    "AGR": "Argelia",
    "AND": "Andorra",
    "ANG": "Angola",
    "ANT": "Antigua",
    "ARG": "Argentina",
    "ARM": "Armenia",
    "ARU": "Aruba",
    "ASA": "American Samoa",
    "AUS": "Australia",
    "AUT": "Austria",
    "AZE": "Azerbaijan",
    "BAH": "Bahamas",
    "BAN": "Bangladesh",
    "BAR": "Barbados",
    "BDI": "Burundi",
    "BEL": "Belgium",
    "BEN": "Benin",
    "DAY": "Dahomey",
    "BER": "Bermuda",
    "BHU": "Bhutan",
    "BIH": "Bosnia and Herzegovina",
    "BIZ": "Belize",
    "BLR": "Belarus",
    "BOL": "Bolivia",
    "BOT": "Botswana",
    "BRA": "Brazil",
    "BRN": "Bahrain",
    "BRU": "Brunei",
    "BUL": "Bulgaria",
    "BUR": "Burkina Faso",
    "CAF": "Central African Republic",
    "CAM": "Cambodia",
    "CAB": "Khmer Republic",
    "CAN": "Canada",
    "CAY": "Cayman Islands",
    "CGO": "Republic of the Congo",
    "CHA": "Chad",
    "CHI": "Chile",
    "CIL": "Cile",
    "CHN": "China",
    "CIV": "Ivory Coast",
    "IVC": "Costa de Marfil",
    "CMR": "Cameroon",
    "COD": "Democratic Republic of the Congo",
    "COK": "Cook Islands",
    "COL": "Colombia",
    "COM": "Comoros",
    "CPV": "Cape Verde",
    "CRC": "Costa Rica",
    "CRO": "Croatia",
    "CUB": "Cuba",
    "CYP": "Cyprus",
    "CZE": "Czech Republic",
    "DEN": "Denmark",
    "DJI": "Djibouti",
    "DMA": "Dominica",
    "DOM": "Dominican Republic",
    "ECU": "Ecuador",
    "EGY": "Egypt",
    "RAU": "United Arab Republic",
    "ERI": "Eritrea",
    "ESA": "El Salvador",
    "ESP": "Spain",
    "EST": "Estonia",
    "ETH": "Ethiopia",
    "FIJ": "Fiji",
    "FIN": "Finland",
    "FRA": "France",
    "FSM": "Federated States of Micronesia",
    "GAB": "Gabon",
    "GAM": "The Gambia",
    "GBR": "United Kingdom",
    "GBS": "Guinea-Bissau",
    "GEO": "Georgia",
    "GEQ": "Equatorial Guinea",
    "GER": "Germany",
    "GHA": "Ghana",
    "GRE": "Greece",
    "GRN": "Grenada",
    "GUA": "Guatemala",
    "GUI": "Guinea",
    "GUM": "Guam",
    "GUY": "Guyana",
    "HAI": "Haiti",
    "HKG": "Hong Kong",
    "HON": "Honduras",
    "HUN": "Hungary",
    "UNG": "Ungheria",
    "INA": "Indonesia",
    "IND": "India",
    "IRI": "Iran",
    "IRL": "Ireland",
    "IRQ": "Iraq",
    "ISL": "Iceland",
    "ISR": "Israel",
    "ISV": "Virgin Islands",
    "ITA": "Italy",
    "IVB": "British Virgin Islands",
    "JAM": "Jamaica",
    "JOR": "Jordan",
    "JPN": "Japan",
    "KAZ": "Kazakhstan",
    "KEN": "Kenya",
    "KGZ": "Kyrgyzstan",
    "KIR": "Kiribati",
    "KOR": "South Korea",
    "KOS": "Kosovo",
    "KSA": "Saudi Arabia",
    "KUW": "Kuwait",
    "LAO": "Laos",
    "LAT": "Latvia",
    "LBA": "Libya",
    "LBN": "Lebanon",
    "LBR": "Liberia",
    "LCA": "Saint Lucia",
    "LES": "Lesotho",
    "LIE": "Liechtenstein",
    "LTU": "Lithuania",
    "LUX": "Luxembourg",
    "MAD": "Madagascar",
    "MAR": "Morocco",
    "MAS": "Malaysia",
    "MAW": "Malawi",
    "MDA": "Moldova",
    "MDV": "Maldives",
    "MEX": "Mexico",
    "MGL": "Mongolia",
    "MHL": "Marshall Islands",
    "MKD": "North Macedonia",
    "MLI": "Mali",
    "MLT": "Malta",
    "MNE": "Montenegro",
    "MON": "Monaco",
    "MOZ": "Mozambique",
    "MRI": "Mauritius",
    "MTN": "Mauritania",
    "MYA": "Myanmar",
    "BIR": "Burma",
    "NAM": "Namibia",
    "NCA": "Nicaragua",
    "NED": "Netherlands",
    "NEP": "Nepal",
    "NGR": "Nigeria",
    "NIG": "Niger",
    "NOR": "Norway",
    "NRU": "Nauru",
    "NZL": "New Zealand",
    "OMA": "Oman",
    "PAK": "Pakistan",
    "PAN": "Panama",
    "PAR": "Paraguay",
    "PER": "Peru",
    "PHI": "Philippines",
    "PLE": "Palestine",
    "PLW": "Palau",
    "PNG": "Papua New Guinea",
    "POL": "Poland",
    "POR": "Portugal",
    "PRK": "North Korea",
    "PUR": "Puerto Rico",
    "QAT": "Qatar",
    "ROU": "Romania",
    "RSA": "South Africa",
    "RUS": "Russia",
    "RWA": "Rwanda",
    "SAM": "Samoa",
    "SEN": "Senegal",
    "SEY": "Seychelles",
    "SGP": "Singapore",
    "SKN": "Saint Kitts and Nevis",
    "SLE": "Sierra Leone",
    "SLO": "Slovenia",
    "SM:R": "San Marino",
    "SOL": "Solomon Islands",
    "SOM": "Somalia",
    "SRB": "Serbia",
    "SRI": "Sri Lanka",
    "SSD": "South Sudan",
    "SUD": "Sudan",
    "SUI": "Switzerland",
    "SUR": "Suriname",
    "SVK": "Slovakia",
    "SWE": "Sweden",
    "SWZ": "Eswatini",
    "SYR": "Syria",
    "TAN": "Tanzania",
    "TGA": "Tonga",
    "THA": "Thailand",
    "TJK": "Tajikistan",
    "TKM": "Turkmenistan",
    "TOG": "Togo",
    "TPE": "Taipei",
    "TTO": "Trinidad and Tobago",
    "TUN": "Tunisia",
    "TUR": "Turkey",
    "TUV": "Tuvalu",
    "UAE": "United Arab Emirates",
    "UGA": "Uganda",
    "UKR": "Ukraine",
    "URU": "Uruguay",
    "USA": "United States",
    "UZB": "Uzbekistan",
    "VAN": "Vanuatu",
    "VEN": "Venezuela",
    "VIE": "Vietnam",
    "VIN": "Saint Vincent and the Grenadines",
    "YEM": "Yemen",
    "ZAM": "Zambia",
    "ZIM": "Zimbabwe",
}
